!pip install numpy

In [2]:
import numpy as np

In [3]:
arra=np.array([1,2,3,4,5])

In [4]:
arra

array([1, 2, 3, 4, 5])

In [5]:
arra2=np.array([[1,2,3],[4,5,6]])

In [6]:
arra2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arra.ndim

1

In [8]:
arra2.ndim

2

In [9]:
arra_float=np.array([1,2,3], dtype=np.float64)

In [10]:
zeros_arr = np.zeros((5, 4)) 

In [11]:
zeros_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
one_arr=np.ones((3,3))

In [13]:
one_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
one_arr=np.ones((5,4),dtype=int)

In [15]:
one_arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
empty_arr=np.empty((4,4))

In [22]:
empty_arr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.11522054e-307],
       [1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306],
       [8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
        1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307]])

In [23]:
identity=np.eye(3)

In [24]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
identity1=np.eye(5)

In [26]:
identity1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
range_arr=np.arange(1,10,2)

In [28]:
range_arr

array([1, 3, 5, 7, 9])

In [29]:
linspace=np.linspace(0,1,10)

In [30]:
linspace

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [31]:
Linspace1=np.linspace(2,4,9)

In [32]:
Linspace1

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  ])

In [34]:
random_int=np.random.randint(5,10,(3,3))

In [35]:
random_int

array([[7, 8, 7],
       [8, 9, 8],
       [5, 7, 9]], dtype=int32)

In [37]:
random_float=np.random.random((3,4))

In [40]:
random_float1=np.random.random((3,4))

In [41]:
random_float

array([[0.89027475, 0.24092912, 0.39787317, 0.27604289],
       [0.49891638, 0.99894803, 0.2779044 , 0.05122483],
       [0.6056794 , 0.59613513, 0.47490772, 0.14110765]])

In [44]:
random1=np.random.randint(3,4,(4,5))

In [45]:
random1

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=int32)

In [47]:
normal_dist=np.random.normal(0,1,(3,3))

In [48]:
normal_dist

array([[ 0.40361785,  1.36952019, -0.81927196],
       [-1.49670683,  0.45645144, -1.077887  ],
       [-0.12026222,  1.05919266,  1.63109236]])

In [49]:
normal=np.random.normal(66,78,(3,3))

In [50]:
normal

array([[102.71423739,  83.92884599,  44.71242213],
       [ 38.15696266,  70.54869322, 120.51753253],
       [ 96.6825681 ,  98.07573658, -53.29399187]])

In [53]:
np.random.seed(42)
random1=np.random.randint(2,9,(3,3))

In [54]:
random1

array([[8, 5, 6],
       [8, 4, 6],
       [6, 8, 3]], dtype=int32)

In [63]:
sample_array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [64]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
sample_array.size

12

In [67]:
sample_array.shape

(3, 4)

In [69]:
sample_array.max()

np.int64(12)

In [70]:
sample_array.min()

np.int64(1)

In [71]:
sample_array.std()

np.float64(3.452052529534663)

In [72]:
sample_array.var()

np.float64(11.916666666666666)

In [74]:
sample_array.ndim

2

In [75]:
sample_array.dtype

dtype('int64')

In [76]:
sample_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
sample_array[2]

array([ 9, 10, 11, 12])

In [78]:
sample_array[0]

array([1, 2, 3, 4])

In [80]:
sample_array[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
sample_array[0:2,1:2]

array([[2],
       [6]])

In [82]:
sample_array[1:2,0:1]

array([[5]])

In [83]:
sample_array[2:3,1:3]

array([[10, 11]])

In [84]:
sample_array


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
sample_array[0:3,3:4]


array([[ 4],
       [ 8],
       [12]])

In [89]:
original=np.arange(12)

In [91]:
original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [92]:
original=np.arange(15)

In [93]:
original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])