In [13]:
class Vehicle:
    def start(self):
        print("vehicle started")
        

class car(Vehicle):
    def drive(self, petrol, disel, electric):
        self.petrol=petrol
        self.disel=disel
        self.eletric=electric
        print("driving a car")

class bike(Vehicle):
    def ride(self, petrol, electric):
        self.petrol=petrol
        self.electric=electric
        print("riding a bike")

In [14]:
obj = Vehicle()

In [15]:
obj.start()

vehicle started


In [18]:
obj=car()

In [19]:
obj=bike()

In [24]:
obj.

vehicle started


In [1]:
import numpy as np


In [2]:
original

NameError: name 'original' is not defined

In [3]:
original = np.arange(12) 

In [4]:
original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
sample_arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
sample_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
original.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
original.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
sample_arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [14]:
sample_arr.ndim

2

In [15]:
sample_arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
sample_arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [17]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [18]:
a+b

array([ 6,  8, 10, 12])

In [19]:
b-a

array([4, 4, 4, 4])

In [20]:
a-b

array([-4, -4, -4, -4])

In [21]:
a*b

array([ 5, 12, 21, 32])

In [22]:
a**b

array([    1,    64,  2187, 65536])

In [23]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [24]:
data=np.random.normal(50,15,100)

In [25]:
data

array([23.48337603, 29.27779981, 47.20483175, 40.49144552, 41.02189951,
       60.3133174 , 46.40704703, 22.45740143, 63.21022145, 78.06903421,
       56.686861  , 41.62273625, 51.7147197 , 50.90983884, 51.28663468,
       57.57625686, 57.49793852, 35.80833236, 63.47799968, 44.47560952,
       48.42646636, 32.99615156, 45.67061496, 62.46953062, 53.79002236,
       56.99127699, 15.67333996, 78.21478196, 30.38664565, 60.96810522,
       55.57368256, 38.25396138, 24.41156524, 57.6759764 , 57.33451841,
       60.49008066, 51.72125641, 26.66926354, 54.60374897, 25.09984688,
       49.73722909, 52.73182924, 59.56592182, 61.84075607, 31.62098189,
       52.2451993 , 10.09046888, 65.77724866, 48.82755964, 48.8928688 ,
       31.86169239, 59.11547134, 44.9438366 , 49.39521802, 61.68491363,
       42.60519931, 53.17827752, 59.34719228, 48.09865119, 55.06439513,
       33.34650304, 43.64079685, 39.02292246, 37.05977767, 43.13609886,
       61.81846391, 69.59371675, 86.59976404, 43.52472601, 48.10

In [27]:
data.mean()

np.float64(48.24851235796491)

In [28]:
data.mean()

np.float64(48.24851235796491)

In [29]:
data.std()

np.float64(14.944377877283364)

In [31]:
data.shape

(100,)

In [33]:
data.max()

np.float64(86.59976404124662)

In [34]:
data.min()

np.float64(10.090468881152873)

In [39]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr3=np.array([[9,10],[11,12]])

In [40]:
arr1

array([[1, 2],
       [3, 4]])

In [41]:
arr2

array([[5, 6],
       [7, 8]])

In [42]:
arr3

array([[ 9, 10],
       [11, 12]])

In [43]:
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [44]:
np.stack((arr1,arr2,arr3))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [45]:
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])